-- =====================================================
-- FIX: Update REPORTING_TEST user with C#-generated hash
-- Run this if login fails (hash mismatch between SQL and C#)
-- =====================================================
-- Password: Test123!
-- Hash generated by C# SHA1 UTF-8 (AuthenticationService)
-- =====================================================

USE [pscentral]
GO

UPDATE tbl_User
SET UserPassword = '0C6BA03885F3AAE765FBF20F07F514A44DBDA30A'
WHERE pk_UserCode = 'REPORTING_TEST'

IF @@ROWCOUNT > 0
    PRINT 'Password updated. Login with: REPORTING_TEST / Test123!'
ELSE
    PRINT 'User REPORTING_TEST not found.'
GO
